import { Inter } from "next/font/google";
import Head from 'next/head';
import "./globals.css";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Matlista",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
